config/routes.rb
Rails.application.routes.draw do
  
  root 'events#index'
  devise_for :users, controllers: { registrations: 'registrations' }
  
  resources :events do
    resources :surveys, except: [:edit, :update]
    resources :papers do
      resources :comments
      resources :reviews
      resources :assingments
      resources :classrooms
    end
  end

  resources :users, except: [:create, :show]

  post 'create_user' => 'users#create', as: :create_user
  get '/documents' => 'papers#list_all'
  get '/my_documents' => 'papers#my_documents'
  get '/assigned_tutor' => 'papers#list_assigned_tutor'
  get '/assigned_relator' => 'papers#list_assigned_relator'
  get '/users/change_password' => 'users#change_password'
  post '/users/update_password' => 'users#update_password'
  get '/events/:event_id/papers/:id/edit_status' => 'papers#edit_status'
  patch '/events/:event_id/papers/:id' => 'papers#update_status'   

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :papers
    has_one :survey

    validates_presence_of :name
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.where(:career => current_user.career)
  end

 
  def show
     # GET /events/1
    # GET /events/1.json
  end

  # GET /events/new
  def new
    @event = Event.new
  end

 
  def edit
     # GET /events/1/edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

      if @event.save
        redirect_to events_path
      else
        render :new
      end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    if @event.update(event_params)
      redirect_to events_path
    else
      render :edit
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:semester, :year, :name, :limit_date, :career)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="row">
  <div class="col s12 m8 offset-m2">
    <div class="card brown lighten-5">
      <div class="card-content">
        <% if event.new_record?%>
          <h4 class="align center">Nuevo Evento</h4>
        <%else%>
          <h4 class="align center">Editar Evento</h4>
        <%end%>
        <%= form_with(model: event, local: true, id: :event_form) do |form| %>
          <% if event.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

              <ul>
              <% event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

        <div class="row">
          <div class="input-field col s6">
            <%= form.label :semester, 'Semestre *', class: 'active' %>
            <%= form.select :semester, ['Primer','Segundo'], include_blank: 'Elige el semestre', required:"" %>
          </div>

          <div class="input-field col s6">
            <%= form.label :year, 'Año *', class: 'active' %>
            <%= form.select :year, ['2019','2020','2021','2022','2023'] %>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s6">
            <%= form.label :name, 'Nombre del evento *' %>
            <%= form.text_field :name, class: "validate" %>
          </div>
          <div class="input-field col s6">
            <%= form.label :career, 'Carrera *', class: 'active' %>
            <%= form.select :career, ['Ingeniería de Sistemas', 'Ingeniería Ambiental', 'Ingeniería Civil', 'Ingeniería Mecatrónica'], include_blank: 'Elige la carrera' %>
          </div>
        </div>


          <div class="input-field">
            <%= form.label :limit_date, 'Fecha límite de recepción de documentos *' %>
            <%= form.text_field :limit_date, class: "datepicker", :value => (I18n.localize(event.limit_date, format: '%d %b, %Y') if event.limit_date.present?) %>
          </div>
          <div>
            <p class="required-alert">Los campos marcados con * son obligatorios.</p><br>
          </div>

          <div class="center-align">
            <%= button_tag(class: 'btn-small waves-effect waves-light') do %>
              <% event.new_record? ? 'Registrar evento' : 'Editar evento' %>
            <% end %>
          </div>
        <% end %>
      
      </div>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<%= render 'form', event: @event %>

app/views/events/index.html.erb
<h3 class="center-align">Eventos</h3>

<table>
  <thead class="header-row">
    <tr>
      <th>Nombre</th>
      <th>Carrera</th>
      <th>Semestre</th>
      <th>Año</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <% if current_user.estudiante? %>
        <tr>
          <td><%= link_to event.name, event_papers_path(event), class: 'link-to-text' %></td>
          <td><%= event.career %></td>
          <td><%= event.semester %></td>
          <td><%= event.year %></td>
        </tr>
      <% else %>
        <tr>
          <td><%= link_to event.name, event_papers_path(event), class: 'link-to-text' %></td>
          <td><%= event.career %></td>
          <td><%= event.semester %></td>
          <td><%= event.year %></td>
          <% if current_user.admin_role? || current_user.professor_role? %>
            <td><%= link_to edit_event_path(event), class: 'waves-effect btn-floating btn-small grey' do %>
              <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Editar Evento'>edit</em>
              <% end %>
            </td>
            <td>
              <% if event.survey.present? %>
                <%= link_to event_survey_path(event, event.survey), class: "waves-effect btn-floating btn-small grey" do %>
                    <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Ver Form. Revisión'>view_list</em>
                <% end %>
              <% else %>
                <%= link_to new_event_survey_path(event), class: "waves-effect btn-floating btn-small grey" do %>
                    <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Crear Form. Revisión'>assignment</em>
                <% end %>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Semestre:</strong>
  <%= @event.semester %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @event.name %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>